import { useEffect, useState } from 'react'
import { Download, Trash2 } from 'lucide-react'
import { Alert, AlertDescription } from '@/components/ui/alert'
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from '@/components/ui/alert-dialog'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { apiFetch, apiJson } from '../../lib/api'
import { downloadRecording } from '../../lib/recordingDownload'
import { useI18n } from '../../lib/i18n'
type RecordingInfo = { available: boolean; deleted: boolean; can_delete: boolean; filename: string; size_bytes: number }
export function SavedRecordingActions({ noteId, title, onDeleted }: { noteId: string; title: string; onDeleted: () => void }) { const { locale } = useI18n(); const zh = locale.startsWith('zh'); const [info, setInfo] = useState<RecordingInfo | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  useEffect(() => { let active = true; void apiJson<RecordingInfo>(`/api/notes/${noteId}/recording`).then(result => { if (active) setInfo(result) }).catch(cause => { if (active) setError(String(cause)) }); return () => { active = false } }, [noteId])
  const download = async () => { setBusy(true); setError(''); try { const response = await apiFetch(`/api/notes/${noteId}/media`); if (!response.ok) throw new Error(zh ? '录制下载失败，请重试' : 'Download failed'); downloadRecording(await response.blob(), title, info?.filename) } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)) } finally { setBusy(false) } }
  const remove = async () => { setBusy(true); setError(''); try { document.querySelectorAll<HTMLMediaElement>('audio, video').forEach(media => { media.pause(); media.removeAttribute('src'); media.load() }); await apiJson(`/api/notes/${noteId}/recording`, { method: 'DELETE' }); setInfo(info ? { ...info, available: false, deleted: true } : null); onDeleted() } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)) } finally { setBusy(false) } }
  return <div className="grid gap-3 border-b bg-card px-4 py-3"><div className="flex flex-wrap items-center gap-2"><Badge variant="secondary">{zh ? '原始录制' : 'Original recording'}{info?.available ? ` · ${(info.size_bytes / 1024 / 1024).toFixed(1)} MB` : ''}</Badge>{info?.deleted ? <span className="text-sm text-muted-foreground">{zh ? '文件已删除，纪要和转写已保留' : 'Recording deleted; notes and transcript retained'}</span> : null}{info?.available ? <Button variant="outline" size="sm" disabled={busy} onClick={() => void download()}><Download />{zh ? '下载' : 'Download'}</Button> : null}{info?.available && info.can_delete ? <AlertDialog><AlertDialogTrigger asChild><Button variant="ghost" size="sm" disabled={busy} className="text-destructive hover:text-destructive"><Trash2 />{zh ? '删除录制' : 'Delete recording'}</Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{zh ? '删除录制文件？' : 'Delete recording?'}</AlertDialogTitle><AlertDialogDescription>{zh ? '录制及音频副本会永久删除，文字纪要、转写和截图会保留。' : 'The recording is permanently deleted. Notes, transcript and screenshots are retained.'}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>{zh ? '取消' : 'Cancel'}</AlertDialogCancel><AlertDialogAction onClick={() => void remove()}>{zh ? '确认删除' : 'Delete'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog> : null}</div>{info?.available && !info.can_delete ? <p className="text-xs text-muted-foreground">{zh ? '文件被共用或无法验证归属，仅支持下载' : 'Shared or unverified recording: download only'}</p> : null}{error ? <Alert variant="destructive"><AlertDescription>{error}</AlertDescription></Alert> : null}</div> }
