import * as React from 'react'
import { ArrowDown } from 'lucide-react'
import { StickToBottom, useStickToBottomContext } from 'use-stick-to-bottom'
import { Button } from './button'
import { cn } from '@/lib/utils'

export function Conversation({ className, ...props }: React.ComponentProps<typeof StickToBottom>) { return <StickToBottom className={cn('relative flex min-h-0 flex-1 flex-col overflow-hidden', className)} resize="smooth" initial="smooth" {...props} /> }
export function ConversationContent({ className, ...props }: React.ComponentProps<typeof StickToBottom.Content>) { return <StickToBottom.Content className={cn('flex flex-col gap-4 p-4', className)} {...props} /> }
export function ConversationEmptyState({ title, description, icon }: { title: string; description?: string; icon?: React.ReactNode }) { return <div className="flex flex-1 flex-col items-center justify-center gap-3 px-6 py-16 text-center"><div className="flex size-12 items-center justify-center rounded-2xl bg-accent text-accent-foreground">{icon}</div><div><p className="font-medium">{title}</p>{description ? <p className="mt-1 max-w-sm text-sm leading-6 text-muted-foreground">{description}</p> : null}</div></div> }
export function ConversationScrollButton() { const { isAtBottom, scrollToBottom } = useStickToBottomContext(); if (isAtBottom) return null; return <Button variant="secondary" size="icon" className="absolute bottom-4 left-1/2 -translate-x-1/2 rounded-full shadow-lg" onClick={() => scrollToBottom()}><ArrowDown /></Button> }
export function ConversationMessage({ speaker, time, children, active }: { speaker: string; time?: string; children: React.ReactNode; active?: boolean }) { return <article aria-current={active ? 'true' : undefined} className={cn('flex gap-3 rounded-2xl border bg-card p-4 shadow-sm', active && 'border-primary/30 bg-accent/40')}><div className="flex size-9 shrink-0 items-center justify-center rounded-full bg-secondary text-xs font-semibold">{speaker.slice(0, 2)}</div><div className="min-w-0 flex-1"><div className="mb-1 flex items-center gap-2"><span className="text-sm font-semibold">{speaker}</span>{time ? <span className="text-xs text-muted-foreground">{time}</span> : null}{active ? <span className="size-2 animate-pulse rounded-full bg-primary" /> : null}</div><div className="text-sm leading-6 text-foreground/90">{children}</div></div></article> }
