[package]
name = "vinote"
version = "0.3.0"
description = "VINote desktop app"
authors = ["VINote"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "vinote_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["macos-private-api"] }
tauri-plugin-opener = "2"

[target.'cfg(target_os = "macos")'.dependencies]
block2 = "0.6.2"
objc2 = "0.6.4"
objc2-av-foundation = { version = "0.3.1", features = ["AVCaptureDevice", "AVMediaFormat"] }
