import { TranscriptionProgress } from './TranscriptionProgress'
import { useEffect, useState } from 'react'
import { CheckCircle2, ChevronDown, Download, FileAudio, FileText, FileVideo, Play, RotateCcw, Sparkles, Trash2 } from 'lucide-react'
import { Alert, AlertDescription } from '@/components/ui/alert'
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from '@/components/ui/alert-dialog'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { deleteLocalRecording, getRecordedAudio, type PendingMeeting } from '../../lib/audioStorage'
import { downloadRecording } from '../../lib/recordingDownload'
import { useI18n } from '../../lib/i18n'

interface LocalRecordingCardProps { recording: PendingMeeting; onDeleted: () => void; onOpenNote?: (noteId: string) => void }
const stageCopy: Record<PendingMeeting['processingStatus'], string> = { idle: '尚未生成纪要', queued: '等待处理', preparing_media: '准备和校验媒体', transcribing: '云端转写完整音频', diarizing: '区分说话人', aligning: '对齐逐字稿', analyzing_video: '分析代表画面', generating: '生成并校验纪要', saving_result: '保存结果', completed: '纪要已完成', failed: '处理失败' }

export function LocalRecordingCard({ recording, onDeleted, onOpenNote }: LocalRecordingCardProps) {
  const { locale } = useI18n(); const zh = locale.startsWith('zh')
  const [url, setUrl] = useState(''); const [error, setError] = useState(''); const [deleting, setDeleting] = useState(false); const [expanded, setExpanded] = useState(false)
  const title = recording.options.title || (zh ? '未命名会议' : 'Untitled meeting')
  const isVideo = recording.options.meetingType === 'video' || recording.options.screen
  const processing = !['idle', 'completed', 'failed'].includes(recording.processingStatus)
  const Icon = isVideo ? FileVideo : FileAudio
  useEffect(() => () => { if (url) URL.revokeObjectURL(url) }, [url])
  const load = async (download: boolean) => { setError(''); try { const blob = await getRecordedAudio(recording.id); if (!blob) throw new Error(zh ? '找不到此设备上的录制文件' : 'Recording not found on this device'); if (download) downloadRecording(blob, title); else { if (url) URL.revokeObjectURL(url); setUrl(URL.createObjectURL(blob)); setExpanded(true) } } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)) } }
  const remove = async () => { setDeleting(true); setError(''); setUrl(''); try { await deleteLocalRecording(recording.id, recording.ownerId); onDeleted() } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)) } finally { setDeleting(false) } }
  const restore = () => window.dispatchEvent(new CustomEvent('vinote-restore-meeting', { detail: recording }))
  const statusText = zh ? stageCopy[recording.processingStatus] : recording.processingStatus.replace(/_/g, ' ')

  return <article className="interactive-card motion-rise flex min-h-72 flex-col overflow-hidden rounded-2xl border bg-card shadow-sm">
    <button type="button" onClick={() => setExpanded(value => !value)} className="flex items-start gap-4 p-5 text-left"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-muted"><Icon className="size-5" /></span><span className="min-w-0 flex-1"><span className="block truncate font-semibold">{title}</span><span className="mt-1 block text-xs text-muted-foreground">{new Date(recording.startedAt).toLocaleString()} · {Math.floor(recording.elapsedSeconds / 60)}:{String(recording.elapsedSeconds % 60).padStart(2, '0')}</span></span><span className="flex items-center gap-2"><Badge variant="secondary">{isVideo ? (zh ? '视频' : 'Video') : (zh ? '音频' : 'Audio')}</Badge><ChevronDown className={expanded ? 'size-4 rotate-180 transition-transform' : 'size-4 transition-transform'} /></span></button>
    {expanded ? <div className="animate-in border-y bg-muted/20 p-4 fade-in slide-in-from-top-2 duration-300">{url ? isVideo ? <video src={url} controls className="max-h-72 w-full rounded-xl bg-black" /> : <audio src={url} controls autoPlay className="w-full" /> : <button type="button" onClick={() => void load(false)} className="flex min-h-32 w-full flex-col items-center justify-center rounded-xl border border-dashed bg-background text-sm text-muted-foreground"><Play className="mb-2 size-5" />{zh ? '点击加载并回放' : 'Load and play'}</button>}</div> : null}
    <div className="flex flex-1 flex-col gap-4 p-5 pt-3"><div className="rounded-xl border bg-muted/25 p-4"><div className="flex items-start gap-3">{recording.processingStatus === 'completed' ? <CheckCircle2 className="mt-0.5 size-5 text-emerald-600" /> : <FileText className="mt-0.5 size-5 text-muted-foreground" />}<div className="min-w-0 flex-1"><p className="text-sm font-medium">{statusText}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{recording.processingStatus === 'failed' ? recording.processingError || (zh ? '原始媒体已保留，可重试。' : 'Original media is preserved and retryable.') : processing ? (zh ? '后台处理中，录制控制已经退出。' : 'Processing in the background; capture controls are closed.') : recording.processingStatus === 'completed' ? (zh ? '在详情中查看带说话人的逐字稿、代表画面证据和纪要。' : 'Open details for transcript, visual evidence and notes.') : (zh ? '原始媒体已保存在本机，可播放、下载或生成纪要。' : 'Original media is saved locally.')}</p></div></div></div>
      {recording.processingStatus === 'transcribing' ? <TranscriptionProgress processedSeconds={recording.processedSeconds} totalSeconds={recording.totalSeconds} etaSeconds={recording.etaSeconds} zh={zh} /> : null}
      <div className="mt-auto grid gap-2">{recording.processingStatus === 'failed' ? <Alert variant="destructive"><AlertDescription>{recording.failedStage ? (zh ? '失败阶段：' : 'Failed stage: ') + (stageCopy[recording.failedStage as keyof typeof stageCopy] || recording.failedStage) + '。' : ''}{recording.processingError}</AlertDescription></Alert> : null}{recording.processingStatus === 'completed' && recording.noteId ? <Button onClick={() => onOpenNote?.(recording.noteId!)}><FileText />{zh ? '查看会议纪要' : 'Open meeting notes'}</Button> : <Button disabled={processing || deleting} onClick={restore}>{recording.processingStatus === 'failed' ? <RotateCcw /> : <Sparkles />}{processing ? statusText : recording.processingStatus === 'failed' ? (zh ? '重试会后处理' : 'Retry processing') : (zh ? '生成会议纪要' : 'Generate meeting notes')}</Button>}
        <div className="grid grid-cols-3 gap-2"><Button variant="outline" size="sm" onClick={() => void load(false)}><Play />{zh ? '预览' : 'Preview'}</Button><Button variant="outline" size="sm" onClick={() => void load(true)}><Download />{zh ? '下载文件' : 'Download file'}</Button><AlertDialog><AlertDialogTrigger asChild><Button variant="ghost" size="sm" disabled={processing || deleting} className="text-destructive hover:text-destructive"><Trash2 />{zh ? '删除本地记录' : 'Delete local record'}</Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{zh ? '删除本地记录及原始媒体？' : 'Delete local record and media?'}</AlertDialogTitle><AlertDialogDescription>{zh ? '删除此设备上的记录条目与原始音视频；已保存到服务端的纪要和逐字稿不受影响。尚未完成处理的记录将无法继续生成。' : 'This removes the local original media. Saved server notes and transcripts remain.'}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>{zh ? '取消' : 'Cancel'}</AlertDialogCancel><AlertDialogAction disabled={deleting} onClick={() => void remove()}>{zh ? '确认删除本地记录' : 'Delete local record'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div>{error ? <Alert variant="destructive"><AlertDescription>{error}</AlertDescription></Alert> : null}</div>
    </div>
  </article>
}
